import turtle
turtle.forward(250)
turtle.shape("circle")
turtle.shapesize(5)
turtle.right(270)
turtle.forward(250)
turtle.shape("square")
turtle.forward(250)
turtle.shape("triangle")
turtle.forward(250)